[package]
name = "crab_nat"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Andersen <ryco117@gmail.com>"]
description = "A pure Rust library implementation of a client for both the NAT Port Mapping Protocol (NAT-PMP) and the Port Control Protocol (PCP)."
license = "MIT"
repository = "https://github.com/ryco117/crab_nat"

[dependencies]
anyhow = "1.0.79"
bytes = "1.5.0"
displaydoc = "0.2.4"
num_enum = "0.7.2"
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
clap = { version = "4.4.18", features = ["derive"] }
default-net = "0.21.0"

[[example]]
name = "client"
